### ISSUE TITLE
Display bugs

### ISSUE THREAD

**Issue by SkymanOne** [SkyMen-Lab/TheP0ngMobileApp#19]
- I found that some labels and buttons are displayed fully or properly on large devices ([see screenshots](https://imgur.com/a/qicuwyE).
- Scroll doesn't work on About Page

**Comment by Hasnainz** [comment]
I have used a FlexLayout to sort all the elements so it should be more flexible to work on more devices now.

**Comment by SkymanOne** [comment]
has been fixed in #21
