### ISSUE TITLE
No monitoring over app state

### ISSUE THREAD

**Issue by SkymanOne** [SkyMen-Lab/TheP0ngMobileApp#20]
### Problem ❌
When the app crashes for some reason and the user opens it again, the app navigates onto LoginScreen. So, the user joins the same game twice and gets the number of players in a team incremented.
### Possible solutions ✅ 
Either store session data: 
- IsOnGame property and if so, just display MainScreen to keep sending UDP messages to the RouterFilter (*bad way*)- alpha
- Or register app crash and send it to the backend, so the number of users get decremented and the user can properly login into the game again (*good way*) - beta

**Comment by Hasnainz** [comment]
https://github.com/SkyMen-Lab/TheP0ngMobileApp/blob/bugfix/bf-0.1.2.1/ThePongMobile/ThePongMobile/ViewModels/MainPageViewModel.cs

I have implemented the app knowing if the user is on the main screen and if the app sleeps while on the main screen, then it will automatically request leave to the game server and move to the login screen.

**Comment by SkymanOne** [comment]
Has been fixed in #21
